// import { CognitoService } from '../../src/services/cognito.service';
// import {
//   CognitoIdentityProviderClient,
//   AdminDeleteUserCommand,
// } from '@aws-sdk/client-cognito-identity-provider';

// /**
//  * SERVICE LAYER INTEGRATION TESTS
//  *
//  * These tests verify that our CognitoService class correctly interfaces with AWS Cognito.
//  * Unlike router tests, these test the service methods directly without going through tRPC.
//  *
//  * Purpose: Verify AWS SDK integration and service layer logic
//  */

// // Only run if TEST_COGNITO_USER_POOL_ID is set
// const testUserPoolId = process.env.TEST_COGNITO_USER_POOL_ID;
// const runIntegrationTests = testUserPoolId && process.env.RUN_INTEGRATION_TESTS === 'true';

// (runIntegrationTests ? describe : describe.skip)(
//   'CognitoService Integration Tests (Real AWS)',
//   () => {
//     const client = new CognitoIdentityProviderClient({ region: 'us-east-1' });
//     const createdUsers: string[] = [];

//     afterEach(async () => {
//       // Cleanup: Delete any users created during tests
//       for (const email of createdUsers) {
//         try {
//           await client.send(
//             new AdminDeleteUserCommand({
//               UserPoolId: testUserPoolId,
//               Username: email,
//             }),
//           );
//         } catch (error) {
//           console.log(`Could not delete test user ${email}:`, error);
//         }
//       }
//       createdUsers.length = 0;
//     });

//     it('should create user in real Cognito via service method', async () => {
//       const service = new CognitoService();
//       const testEmail = `test-${Date.now()}@example.com`;
//       createdUsers.push(testEmail);

//       // Test the service method directly
//       const result = await service.inviteUser({ email: testEmail });

//       // Verify raw AWS response structure
//       expect(result.User).toBeDefined();
//       expect(result.User?.Username).toBe(testEmail);
//       expect(result.User?.UserStatus).toBe('FORCE_CHANGE_PASSWORD');
//       expect(result.User?.Attributes).toEqual(
//         expect.arrayContaining([
//           expect.objectContaining({ Name: 'email', Value: testEmail }),
//           expect.objectContaining({ Name: 'email_verified', Value: 'true' }),
//         ]),
//       );
//     }, 15000);

//     it('should handle AWS errors correctly in service layer', async () => {
//       const service = new CognitoService();
//       const testEmail = `test-${Date.now()}@example.com`;
//       createdUsers.push(testEmail);

//       // Create user first
//       await service.inviteUser({ email: testEmail });

//       // Try to create same user again - should throw AWS error
//       await expect(service.inviteUser({ email: testEmail })).rejects.toThrow(); // The service should propagate AWS errors
//     }, 15000);

//     it('should handle sign in flow in service layer', async () => {
//       const service = new CognitoService();
//       const testEmail = `test-${Date.now()}@example.com`;
//       createdUsers.push(testEmail);

//       // Create user first
//       await service.inviteUser({ email: testEmail });

//       // Try to sign in with temporary password (this is tricky - temp password is generated by AWS)
//       // In real scenarios, you'd need to know the temp password or set a permanent one
//       try {
//         const result = await service.signIn({
//           email: testEmail,
//           password: 'UnknownTempPassword123!', // This will likely fail
//         });

//         // If it somehow works, we should get a challenge
//         expect(result.ChallengeName).toBe('NEW_PASSWORD_REQUIRED');
//       } catch (error: any) {
//         // Expected to fail because we don't know the temp password
//         expect(error.name).toContain('NotAuthorized');
//       }
//     }, 15000);
//   },
// );
